apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: #entnehmen wir der pod-Datei. aus dem labels-Abschnitt
    app: myapp
    type: frontend