apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod 
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodeloud/examplevotingapp_worker:v1
      