apiVersion: v1
kind: Service
metadata:
  name: backend


spec:
  type: ClusterIP # könnten wir auch weglassen, denn ClusterIP ist default
  ports:
    - port: 80 # Port, wo der Service exposed ist
      targetPort: 80 # Port an dem das backend exposed ist
  selector:
    app: nginx
    tier: backend